<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>10</LangVersion>
    <RollForward>Major</RollForward>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../Source/PlayerDirectoryReporter.cs" Link="PlayerDirectoryReporter.cs" />
  </ItemGroup>
</Project>
